MODULE STACKMOD
    IMPLICIT NONE
    PRIVATE

    PUBLIC STACK

    TYPE::STACK
        INTEGER, ALLOCATABLE, DIMENSION(:)::    ARR
        INTEGER::                               MAXSIZE = 1, CURRENTSIZE = 0
        INTEGER::                               INDEX = 1, PANIC = -999
    CONTAINS
        PROCEDURE::INIT, DESTROY, PUSH, POP, PEEK, GETSIZE
        PROCEDURE, PRIVATE::RESIZE
    END TYPE STACK

CONTAINS

    ! SUBROUTINES
    SUBROUTINE INIT(SELF)
        IMPLICIT NONE
        CLASS(STACK), INTENT(OUT)::SELF
        ALLOCATE(SELF%ARR(1))
    END SUBROUTINE INIT

    SUBROUTINE DESTROY(SELF)
        IMPLICIT NONE
        CLASS(STACK), INTENT(INOUT)::SELF
        DEALLOCATE(SELF%ARR)
    END SUBROUTINE DESTROY

    SUBROUTINE PUSH(SELF, N)
        IMPLICIT NONE
        CLASS(STACK), INTENT(INOUT)::SELF
        INTEGER, INTENT(IN)::N
        IF(SELF%INDEX .GT. SELF%MAXSIZE) CALL SELF%RESIZE()
        SELF%ARR(SELF%INDEX) = N
        SELF%INDEX = SELF%INDEX + 1
        SELF%CURRENTSIZE = SELF%CURRENTSIZE + 1
    END SUBROUTINE PUSH

    SUBROUTINE POP(SELF)
        IMPLICIT NONE
        CLASS(STACK), INTENT(INOUT)::SELF
        IF(SELF%INDEX .GT. 1) THEN
            SELF%INDEX = SELF%INDEX - 1
            SELF%CURRENTSIZE = SELF%CURRENTSIZE - 1
        END IF
    END SUBROUTINE POP

    SUBROUTINE RESIZE(SELF)
        IMPLICIT NONE
        CLASS(STACK), INTENT(INOUT)::SELF
        INTEGER::I
        INTEGER, DIMENSION(SELF%CURRENTSIZE)::NEWARR
        SELF%MAXSIZE = SELF%MAXSIZE * 2
        DO I = 1, SELF%CURRENTSIZE
            NEWARR(I) = SELF%ARR(I)
        END DO
        DEALLOCATE(SELF%ARR)
        ! PRINT*, 'STACK SIZE INCREASED FROM ', SELF%MAXSIZE, ' TO ', SELF%MAXSIZE * 2
        ALLOCATE(SELF%ARR(SELF%MAXSIZE * 2))
        DO I = 1, SELF%CURRENTSIZE
            SELF%ARR(I) = NEWARR(I)
        END DO
    END SUBROUTINE RESIZE

    ! FUNCTIONS
    INTEGER FUNCTION PEEK(SELF)
        CLASS(STACK), INTENT(IN)::SELF
        PEEK = SELF%ARR(SELF%INDEX - 1)
    END FUNCTION PEEK

    INTEGER FUNCTION GETSIZE(SELF)
        CLASS(STACK), INTENT(IN)::SELF
        GETSIZE = SELF%CURRENTSIZE
    END FUNCTION GETSIZE

END MODULE STACKMOD
