! AUTHOR: ZACHARY HASKINS
! DATE: 1/1/2022
! DYNAMIC STACK

MODULE STACKMOD
    IMPLICIT NONE
    PRIVATE

    ! DERRIVED TYPES
    PUBLIC::STACK
    
    ! PUBLIC SUBROUTINES
    PUBLIC::PUSH, DESTROY, POP 

    ! PUBLIC FUNCTIONS
    PUBLIC::TOP, EMPTY, SIZE

    ! TYPES
    TYPE NODE
        INTEGER, ALLOCATABLE::DATA
        CLASS(NODE), POINTER::NEXT => NULL()
    END TYPE NODE

    TYPE STACK
        CLASS(NODE), POINTER::HEAD => NULL()
        INTEGER::SIZE
    END TYPE STACK

    ! INTERFACES
    INTERFACE PUSH
        PROCEDURE::PUSH_NODE
    END INTERFACE PUSH

    INTERFACE EMPTY
        PROCEDURE::CHECK_IF_EMPTY
    END INTERFACE EMPTY

    INTERFACE SIZE
        PROCEDURE::GET_SIZE
    END INTERFACE SIZE

    INTERFACE TOP
        PROCEDURE::GET_TOP
    END INTERFACE TOP

    INTERFACE POP
        PROCEDURE::POP_NODE
    END INTERFACE POP

    INTERFACE DESTROY
        PROCEDURE::DESTROY_STACK
    END INTERFACE DESTROY

    INTERFACE NODE
        PROCEDURE N_CONSTR
    END INTERFACE NODE

CONTAINS

    ! PUBLIC SUBROUTINES
    PURE SUBROUTINE PUSH_NODE(THIS, DATA)
        IMPLICIT NONE
        CLASS(STACK), INTENT(INOUT)::THIS
        INTEGER, INTENT(IN)::DATA
        CLASS(NODE), POINTER::TEMP 
        IF(.NOT. ASSOCIATED(THIS%HEAD)) THEN
            ALLOCATE(THIS%HEAD, SOURCE = N_CONSTR(DATA))
        ELSE
            TEMP => THIS%HEAD
            ALLOCATE(THIS%HEAD, SOURCE = N_CONSTR(DATA))
            THIS%HEAD%NEXT => TEMP 
        END IF
        THIS%SIZE = THIS%SIZE + 1
    END SUBROUTINE PUSH_NODE

    PURE SUBROUTINE POP_NODE(THIS)
        IMPLICIT NONE
        CLASS(STACK), INTENT(INOUT)::THIS
        CLASS(NODE), POINTER::TEMP
        IF(ASSOCIATED(THIS%HEAD)) THEN
            TEMP => THIS%HEAD
            THIS%HEAD => THIS%HEAD%NEXT
            DEALLOCATE(TEMP%DATA)
            THIS%SIZE = THIS%SIZE - 1
        END IF
    END SUBROUTINE POP_NODE

    PURE SUBROUTINE DESTROY_STACK(THIS)
        IMPLICIT NONE
        CLASS(STACK), INTENT(INOUT)::THIS
        CLASS(NODE), POINTER::TEMP 
        DO WHILE(ASSOCIATED(THIS%HEAD))
            TEMP => THIS%HEAD
            THIS%HEAD => THIS%HEAD%NEXT
            DEALLOCATE(TEMP%DATA)
        END DO
        THIS%SIZE = 0
    END SUBROUTINE DESTROY_STACK

    ! PUBLIC FUNCTIONS
    LOGICAL FUNCTION CHECK_IF_EMPTY(THIS)
        IMPLICIT NONE
        CLASS(STACK), INTENT(IN)::THIS
        CHECK_IF_EMPTY = .TRUE.
        IF(ASSOCIATED(THIS%HEAD)) THEN
            CHECK_IF_EMPTY = .FALSE.
        END IF 
    END FUNCTION CHECK_IF_EMPTY

    INTEGER FUNCTION GET_TOP(THIS)
        IMPLICIT NONE
        CLASS(STACK), INTENT(IN)::THIS
        GET_TOP = -999 
        IF(ASSOCIATED(THIS%HEAD)) THEN
            GET_TOP = THIS%HEAD%DATA
        END IF
    END FUNCTION GET_TOP

    INTEGER FUNCTION GET_SIZE(THIS)
        IMPLICIT NONE
        CLASS(STACK), INTENT(IN)::THIS
        GET_SIZE = THIS%SIZE
    END FUNCTION GET_SIZE

    ! PRIVATE SUBROUTINES

    ! PRIVATE FUNCTIONS
    PURE FUNCTION N_CONSTR(DATA)
        INTEGER, INTENT(IN)::DATA
        TYPE(NODE)::N_CONSTR
        ALLOCATE(N_CONSTR%DATA, SOURCE = DATA) 
    END FUNCTION N_CONSTR

END MODULE STACKMOD
