MODULE VECTORMOD
    IMPLICIT NONE
    PRIVATE

    PUBLIC VECTOR

    TYPE::VECTOR
        INTEGER, ALLOCATABLE, DIMENSION(:)::ARR
        INTEGER ::CURRENTSIZE = 0, MAXSIZE = 1, INDEX = 1, PANIC = -999
    CONTAINS
        PROCEDURE::INIT, DESTROY, APPEND, PRINT, GETSIZE, HAS, PREPEND
        PROCEDURE, PRIVATE::RESIZE
    END TYPE VECTOR

CONTAINS

    ! SUBROUTINES
    SUBROUTINE INIT(SELF)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(OUT)::SELF
        ALLOCATE(SELF%ARR(1))
    END SUBROUTINE INIT

    SUBROUTINE DESTROY(SELF)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(INOUT)::SELF
        DEALLOCATE(SELF%ARR)
    END SUBROUTINE DESTROY

    SUBROUTINE APPEND(SELF, N)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(INOUT)::SELF
        INTEGER::N
        IF(SELF%INDEX .GT. SELF%MAXSIZE) THEN
            CALL SELF%RESIZE()
        END IF
        SELF%ARR(SELF%INDEX) = N
        SELF%INDEX = SELF%INDEX + 1
        SELF%CURRENTSIZE = SELF%CURRENTSIZE + 1
    END SUBROUTINE APPEND

    SUBROUTINE PREPEND(SELF, N)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(INOUT)::SELF
        INTEGER::I, N, TEMP1, TEMP
        TEMP = N
        IF(SELF%INDEX .GT. SELF%MAXSIZE) THEN
            CALL SELF%RESIZE()
        END IF
        DO I = 1, SELF%GETSIZE() + 1
            TEMP1 = SELF%ARR(I)
            SELF%ARR(I) = TEMP
            TEMP = TEMP1
        END DO
        ! SELF%ARR(1) = N
        SELF%CURRENTSIZE = SELF%CURRENTSIZE + 1
    END SUBROUTINE PREPEND

    SUBROUTINE PRINT(SELF)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(IN)::SELF
        INTEGER::I
        DO I = 1, SELF%CURRENTSIZE
            PRINT*, SELF%ARR(I)
        END DO
    END SUBROUTINE PRINT

    SUBROUTINE RESIZE(SELF)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(INOUT)::SELF
        INTEGER::I
        INTEGER, DIMENSION(SELF%CURRENTSIZE)::NEWARR
        SELF%MAXSIZE = SELF%MAXSIZE * 2
        DO I = 1, SELF%CURRENTSIZE
            NEWARR(I) = SELF%ARR(I)
        END DO
        DEALLOCATE(SELF%ARR)
        ALLOCATE(SELF%ARR(SELF%MAXSIZE * 2))
        DO I = 1, SELF%CURRENTSIZE
            SELF%ARR(I) = NEWARR(I)
        END DO
    END SUBROUTINE RESIZE

    ! FUNCTIONS
    INTEGER FUNCTION GETSIZE(SELF)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(IN)::SELF
        GETSIZE = SELF%CURRENTSIZE
    END FUNCTION GETSIZE

    LOGICAL FUNCTION HAS(SELF, N)
        IMPLICIT NONE
        CLASS(VECTOR), INTENT(IN)::SELF
        INTEGER::I, N
        HAS = .FALSE.
        DO I = 1, SELF%GETSIZE()
            IF(SELF%ARR(I) .EQ. N) THEN
                HAS = .TRUE.
                EXIT
            END IF
        END DO
    END FUNCTION HAS

END MODULE VECTORMOD
